### ISSUE TITLE
about_InlineScript.md - Formatting Issues, Bad Links

### ISSUE THREAD

**Issue by DouglasPlumley** [PowerShell/PowerShell-Docs#1110]
The website https://msdn.microsoft.com/en-us/powershell/reference/5.1/psworkflow/about/about_inlinescript show imcomplete information from the .md file, looks like maybe a tag didn't get closed?

Site ends with "SYNTAX

InlineScript {
"

Also includes link to http://go.microsoft.com/fwlink/?LinkId=261983 which no longer appears valid.

Thanks!

**Comment by juanpablojofre** [comment]
Closing as resolved in #1127

**Comment by DouglasPlumley** [comment]
Thanks for fixing the formatting issues @juanpablojofre , I still see the bad URL in there, any clues as to where that should point?
