### ISSUE TITLE
Class authoring doc is wrong

### ISSUE THREAD

**Issue by JasonMorgan** [PowerShell/PowerShell-Docs#260]
It states you can use Nested Modules to host DSCResource classes.  You cannot.

**Comment by JasonMorgan** [comment]
https://github.com/PowerShell/PowerShell-Docs/blob/master/dsc/authoringResourceClass.md

This doc.

**Comment by eslesar** [comment]
Thank you for pointing this out! The docs were fixed with #262

**Comment by JasonMorgan** [comment]
Turns out I may have been wrong, Apparently it's my WMF 5 version.

On Thu, Mar 24, 2016 at 3:44 PM, eslesar <notifications@github.com> wrote:

> Thank you for pointing this out! The docs were fixed with #262
> <https://github.com/PowerShell/PowerShell-Docs/pull/262>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/PowerShell/PowerShell-Docs/issues/260#issuecomment-201038490>
>



-- 
Respectfully,
Jason Morgan
jmorgan@f9vs.com
(720) 877-1864
Twitter @rjasonmorgan

**Comment by JasonMorgan** [comment]
Ignore my last, it's still failing with the latest WMF 5 release.  Now it
adds the resource but it always fails to create an instance of the class.

On Thu, Mar 24, 2016 at 9:14 PM, Jason Morgan <jmorgan@f9vs.com> wrote:

> Turns out I may have been wrong, Apparently it's my WMF 5 version.
>
> On Thu, Mar 24, 2016 at 3:44 PM, eslesar <notifications@github.com> wrote:
>
>> Thank you for pointing this out! The docs were fixed with #262
>> <https://github.com/PowerShell/PowerShell-Docs/pull/262>
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PowerShell/PowerShell-Docs/issues/260#issuecomment-201038490>
>>
>
>
>
> --
> Respectfully,
> Jason Morgan
> jmorgan@f9vs.com
> (720) 877-1864
> Twitter @rjasonmorgan
>
>
>


-- 
Respectfully,
Jason Morgan
jmorgan@f9vs.com
(720) 877-1864
Twitter @rjasonmorgan
